### PR TITLE
Add back-tick code blocks

### PR DESCRIPTION
**Pull request by san650**
This addresses #2

### CODE REVIEW

**Comment by WardCunningham** [comment]
This looks a little bleak without the benefit of some css. I think we are all happy with the github flavored markdown look.

The css could be easily applied in style attributes generated with the dom objects. This isn't perfect, but safe and has been used freely in other plugins.

There has been some discussion of having some better styling of code and blockquote tags in the primary style.css. This would be a larger project, of course. The plus is that the HTML plugin would benefit too.
https://github.com/fedwiki/wiki-client/blob/master/client/style.css

The About Markdown Plugin page will need an update. This is easy to edit by launching wiki from within your local repo using the `-d` option to find pages there.

```
wiki -p 4000 -d .
```

**Comment by san650** [comment]
Thanks for looking at the PR.

About having these styles in the global style.css file, It's indeed a larger project and I can tackle that on another PR but I'll need a bit more time for this. For now, I'll update this PR to include the inline styles.

**Comment by WardCunningham** [comment]
Perfect.

**Comment by san650** [comment]
I've updated the PR.

This is how it looks now

screen shot 2015-05-23 at 2 02 09 pm

What do you think?

**Comment by paul90** [comment]
Thanks @san650 

Published as **\+ wiki-plugin-markdown@0.2.3**

Closes #2

**Pull request merged**
