### PR TITLE
Use checkbox for tasks

### PR DESCRIPTION
**Pull request by san650**
This addresses #1

### CODE REVIEW

**Comment by WardCunningham** [comment]
Hmm. I thought I did the command line merge with #8 right but got in a bit of a tangle. Maybe you could revise the pull request? Thanks.

**Comment by san650** [comment]
Thanks for looking at the PR, I've rebased this branch on top of master.

Please, try now

**Comment by paul90** [comment]
Thanks @san650 

Published as **\+ wiki-plugin-markdown@0.2.3**

Closes #1

**Comment by san650** [comment]
Thanks @paul90.

I don't see the release (tag) in github, I do see it in npmjs.org. Maybe you forgot to push the tags to github?

**Pull request merged**
