### PR TITLE
Paul90/better markdown

### PR DESCRIPTION
**Pull request by paul90**
A possible route for providing better markdown support.

### CODE REVIEW

**Comment by WardCunningham** [comment]
Notes: http://ward.asia.wiki.org/correct-markdown.html

**Comment by WardCunningham** [comment]
This all looks great. Happy to see it merged.

**Comment by paul90** [comment]
Published as + wiki-plugin-markdown@0.3.0

**Comment by WardCunningham** [comment]
Administrators, find Plugmatic installer here:
http://ward.asia.wiki.org/correct-markdown.html

**Pull request merged**
